services:
  - type: web
    name: 5az-store
    env: node
    plan: free
    buildCommand: rm -rf .next && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        value: mongodb+srv://abufayaz:r8KFNrpWyn11R22v@cluster0.jmdh0hc.mongodb.net/
      - key: NEXTAUTH_SECRET
        value: changeme_dev_secret_123
      - key: NEXTAUTH_URL
        value: https://5az-store.onrender.com
      - key: RAZORPAY_KEY_ID
        value: rzp_test_placeholder
      - key: RAZORPAY_KEY_SECRET
        value: secret_placeholder
      - key: NEXT_PUBLIC_RAZORPAY_KEY_ID
        value: rzp_test_placeholder
